In [1]:
!pip install numpy
import numpy as np

In [2]:
ar=np.array([10,20,30,40])
print(ar)

[10 20 30 40]


In [3]:
ar.dtype

dtype('int64')

In [4]:
type(ar)

numpy.ndarray

In [5]:
ar_2=np.array({})
print(ar_2)

{}


In [6]:
ar.ndim

1

In [7]:
tarr=np.array([[10,203,40],[34,67,56],[49,48,58]])
print(tarr)

[[ 10 203  40]
 [ 34  67  56]
 [ 49  48  58]]


In [8]:
tarr.ndim

2

In [9]:
tarr.shape

(3, 3)

In [10]:
print(ar)

[10 20 30 40]


In [11]:
l=[10,20,30,40]
print(l)

[10, 20, 30, 40]


In [12]:
l1=[30,40,50,60]
#zip(l,l1)
lsum=[i+j for i,j in zip(l,l1)]
lsum

[40, 60, 80, 100]

In [13]:
ar2=np.array([30,40,50,60])
print(ar2)

[30 40 50 60]


In [14]:
l+l1

[10, 20, 30, 40, 30, 40, 50, 60]

In [15]:
ar1+ar2

NameError: name 'ar1' is not defined

In [ ]:
a=np.array(["apple",45,"cat","dog"])
print(a)
a.dtype

the above type means that it is unicode error.


indexing and slicing

In [ ]:
print(ar)

In [ ]:
print(ar[2])

In [ ]:
print(tarr)

In [ ]:
print(tarr[1,2])

In [16]:
arc=np.array([1,2,3,4,5],dtype="complex")
print(arc)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# creating an array with the help of arrange method

In [ ]:
#import numpy as np
np.arange(1,11)

In [ ]:
x=(np.arange(2,21,2))
print(x)

In [ ]:
np.arange(31,52,3).reshape(7,1)

In [ ]:
np.arange(1,7).reshape(-1,6)

In [ ]:
np.zeros((10,2),dtype="int")

In [ ]:
np.ones((5,5))

In [ ]:
np.random.seed(3)
x=np.random.random((10,5))
print (x)

In [ ]:
np.random.randint(5,10,(5,10))

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype="float").reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [ ]:
print(a1.size)
print(a1)

In [ ]:
print(a2.shape)
print(a2)

In [ ]:
print(a3.shape)
print(a3)

In [ ]:
pip install matplotlib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

a3 = np.arange(8).reshape(2, 2, 2)

fig, axes = plt.subplots(1, 2, figsize=(10, 5))

# Visualize each 2D matrix in a3
for i in range(2):
    axes[i].matshow(a3[i], cmap='viridis')
    axes[i].set_title(f'Matrix {i+1}')
    for (j, k), val in np.ndenumerate(a3[i]):
        axes[i].text(k, j, f'{val}', ha='center', va='center', color='white')

plt.show()


In [ ]:
a2>=15

In [ ]:
a4=np.arange(12,24).reshape(3,4)
print(a4)

In [20]:
a2=np.arange(12,dtype="float").reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [21]:
a2=a2.astype(int)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a2=a2*3
print(a2)

In [ ]:
print(a2+a4)

In [ ]:
print(a4-a2)

ARRAY FUNCTIONS

In [22]:
from numpy.core.fromnumeric import prod
print(np.prod(a2))

0


C:\Users\eshit\AppData\Local\Temp\ipykernel_13292\183508572.py:1: DeprecationWarning: numpy.core.fromnumeric is deprecated and has been renamed to numpy._core.fromnumeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.prod.
  from numpy.core.fromnumeric import prod


In [ ]:
print(np.prod(a4))

In [23]:
print(np.min(a2))

0


In [ ]:
print(np.max(a2))

In [ ]:
print(np.sum(a2))

In [26]:
print(np.mean(a2))

5.5


In [27]:
#finding mean across the rows
np.mean(a2,axis=1)

array([1.5, 5.5, 9.5])

In [ ]:
print(np.std(a2))

In [ ]:
print(np.var(a2))

In [25]:
mat=np.arange(12,24).reshape(4,3)


In [ ]:
print(np.dot(a2,mat))

In [ ]:
#iterating over a matrix.
for i in mat:
    for j in i:
        print(j)
    #print(i)


In [ ]:
for i in np.nditer(mat):
    print(i)
      

In [ ]:
#conversion of 2d to 1d
mat.ravel()